Resources:
# Create the Ec2
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: "t2.micro"
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: devops_01
      ImageId: 'ami-01e7ca2ef94a0ae86'
    
  # Create the SecurityGroup - Enable SSH via port 22
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress: 
        - IpProtocol: tcp 
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
