# using Anchor & Aliases to reduce code repetion
defaults: &defaults
  # use the the Docker Executor
  docker:
    # Use a light weight image | we can use
      - image: circleci/node:13.8.0
  working_directory: ~/project
      
# Use the latest 2.1 version of CircleCI pipeline process engine. 
version: 2.1